/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import com.phone_shop.controller.SupplierController;
import com.phone_shop.model.Supplier;
import com.phone_shop.other.IDGenerator4Int;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author NisalSP9
 */
public class Add_Supliers extends javax.swing.JDialog {

    
    public Add_Supliers(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try{
        int ID =IDGenerator4Int.getNextId("supplier", "Supplier_ID");
        supIDText.setText(Integer.toString(ID));
        }catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(Add_Supliers.this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nicNumber = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        supIDText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        discription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        address = new javax.swing.JLabel();
        mobileNumber = new javax.swing.JLabel();
        mobileNumberText = new javax.swing.JTextField();
        landLineText = new javax.swing.JTextField();
        landLine = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        saveCustomerButton1 = new javax.swing.JButton();
        ResetCustomerButton = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        discriptionText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 10, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        nicNumber.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        nicNumber.setText("Supplier ID");
        getContentPane().add(nicNumber);
        nicNumber.setBounds(10, 100, 130, 30);

        firstName.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        firstName.setText("Name");
        getContentPane().add(firstName);
        firstName.setBounds(10, 140, 130, 30);

        supIDText.setEditable(false);
        getContentPane().add(supIDText);
        supIDText.setBounds(160, 100, 180, 30);

        NameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameTextKeyTyped(evt);
            }
        });
        getContentPane().add(NameText);
        NameText.setBounds(160, 140, 310, 30);

        discription.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        discription.setText("Discription");
        getContentPane().add(discription);
        discription.setBounds(10, 180, 130, 30);

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        addressTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressTextAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(addressTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 280, 420, 80);

        address.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        address.setText("Address");
        getContentPane().add(address);
        address.setBounds(10, 280, 130, 30);

        mobileNumber.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        mobileNumber.setText("Mobile Number");
        getContentPane().add(mobileNumber);
        mobileNumber.setBounds(10, 370, 130, 30);

        mobileNumberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileNumberTextKeyTyped(evt);
            }
        });
        getContentPane().add(mobileNumberText);
        mobileNumberText.setBounds(160, 370, 180, 30);

        landLineText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                landLineTextKeyTyped(evt);
            }
        });
        getContentPane().add(landLineText);
        landLineText.setBounds(160, 410, 180, 30);

        landLine.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        landLine.setText("Land Line");
        getContentPane().add(landLine);
        landLine.setBounds(10, 410, 130, 30);

        email.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        email.setText("Email");
        getContentPane().add(email);
        email.setBounds(10, 450, 130, 30);

        emailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailTextKeyTyped(evt);
            }
        });
        getContentPane().add(emailText);
        emailText.setBounds(160, 450, 420, 30);

        saveCustomerButton1.setFont(new java.awt.Font("Vani", 0, 24)); // NOI18N
        saveCustomerButton1.setText("Save");
        saveCustomerButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(saveCustomerButton1);
        saveCustomerButton1.setBounds(320, 490, 130, 40);

        ResetCustomerButton.setFont(new java.awt.Font("Vani", 0, 24)); // NOI18N
        ResetCustomerButton.setText("Reset");
        ResetCustomerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ResetCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetCustomerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ResetCustomerButton);
        ResetCustomerButton.setBounds(450, 490, 130, 40);

        mainLabel.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainLabel.setText("Add Supplier Details");
        getContentPane().add(mainLabel);
        mainLabel.setBounds(10, 0, 650, 80);

        discriptionText.setColumns(20);
        discriptionText.setRows(5);
        discriptionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discriptionTextKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(discriptionText);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(160, 180, 420, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTextKeyTyped
        char c=evt.getKeyChar();

        if(!(Character.isLetter(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_SPACE||c==KeyEvent.VK_DELETE||c==KeyEvent.VK_ENTER)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_NameTextKeyTyped

    private void addressTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTextAreaKeyTyped
        char c=evt.getKeyChar();

        if(!(Character.isLetter(c)||Character.isDigit(c)||c==KeyEvent.VK_SLASH||c==KeyEvent.VK_SPACE||c==KeyEvent.VK_COMMA||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE||c==KeyEvent.VK_ENTER)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_addressTextAreaKeyTyped

    private void mobileNumberTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileNumberTextKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE||c==KeyEvent.VK_ENTER)){
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_mobileNumberTextKeyTyped

    private void landLineTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_landLineTextKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE||c==KeyEvent.VK_ENTER)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_landLineTextKeyTyped

    private void emailTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyTyped
       

    }//GEN-LAST:event_emailTextKeyTyped

    private void saveCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerButton1ActionPerformed
         if(!(NameText.getText().trim().equals(""))){
            int okayORnot = JOptionPane.showConfirmDialog(null,"Do you really want to ADD this ?","ADD",JOptionPane.YES_NO_OPTION);
        if(okayORnot==0){
        
                                int supID=Integer.parseInt(supIDText.getText());
				String first_Name=NameText.getText();
                                String discription=discriptionText.getText(); 
				String address=addressTextArea.getText();
                                String mobile_Number=mobileNumberText.getText();
                                String landLine=landLineText.getText();
                                String email=emailText.getText();
				
				Supplier supplier=new Supplier(supID, first_Name, discription, address, mobile_Number, landLine, email);
				try{
					int res=SupplierController.addSupplier(supplier);
					if(res>0){
						JOptionPane.showMessageDialog(Add_Supliers.this,"Added");
					}
				}catch(NumberFormatException | SQLException | ClassNotFoundException e){
                                JOptionPane.showMessageDialog(Add_Supliers.this,e.getMessage());
                                }
                                
                                supIDText.setText("");
                                NameText.setText("");
                                discriptionText.setText("");
                                addressTextArea.setText("");
                                mobileNumberText.setText("");
                                landLineText.setText("");
                                emailText.setText("");

                                try{
                                int ID =IDGenerator4Int.getNextId("supplier", "Supplier_ID");
                                supIDText.setText(Integer.toString(ID));
                                }catch (ClassNotFoundException | SQLException ex) {
                                    JOptionPane.showMessageDialog(Add_Supliers.this, ex);
                                }
                                
                                }
        }else{
        getToolkit().beep();
        JOptionPane.showMessageDialog(Add_Supliers.this,"First Name Can't Be Empty !");
        
        }
       

    }//GEN-LAST:event_saveCustomerButton1ActionPerformed

    private void ResetCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetCustomerButtonActionPerformed

        if(!(NameText.getText().trim().equals(""))){

            supIDText.setText("");
            NameText.setText("");
            discriptionText.setText("");
            addressTextArea.setText("");
            mobileNumberText.setText("");
            landLineText.setText("");
            emailText.setText("");

            try{
            int ID =IDGenerator4Int.getNextId("supplier", "Supplier_ID");
            supIDText.setText(Integer.toString(ID));
            }catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(Add_Supliers.this, ex);
            }
        }else{
        getToolkit().beep();
        JOptionPane.showMessageDialog(Add_Supliers.this,"Nothing to reset !");
        
        }

    }//GEN-LAST:event_ResetCustomerButtonActionPerformed

    private void discriptionTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discriptionTextKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_discriptionTextKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Supliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Supliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Supliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Supliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add_Supliers dialog = new Add_Supliers(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameText;
    private javax.swing.JButton ResetCustomerButton;
    private javax.swing.JLabel address;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JLabel discription;
    private javax.swing.JTextArea discriptionText;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel landLine;
    private javax.swing.JTextField landLineText;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel mobileNumber;
    private javax.swing.JTextField mobileNumberText;
    private javax.swing.JLabel nicNumber;
    private javax.swing.JButton saveCustomerButton1;
    private javax.swing.JTextField supIDText;
    // End of variables declaration//GEN-END:variables
}
