/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import com.phone_shop.controller.CreditDetailController;
import com.phone_shop.model.CreditDetailModel;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author NisalSP9
 */
public class CreditDetail extends javax.swing.JDialog {

    
    
    /**
     * Creates new form CreditDetail
     */
    public CreditDetail(java.awt.Frame parent, boolean modal,String amount,String date,String ID) {
        super(parent, modal);
        initComponents();

        Infor.setVisible(false);
        orderIDText.setText(ID);
        currentDateText.setText(date);
        amountText.setText(amount);
        balanceText.setText(amount);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Infor = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        orderIDText = new javax.swing.JTextField();
        currentDateText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        balanceText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rpayment = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        setMinimumSize(new java.awt.Dimension(450, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        Infor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Infor.setForeground(new java.awt.Color(255, 0, 0));
        Infor.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Make sure you will save the ORDER after you have saved Credite Details !");
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Infor.add(jLabel12);
        jLabel12.setBounds(0, 0, 420, 30);

        getContentPane().add(Infor);
        Infor.setBounds(10, 370, 420, 30);

        jLabel4.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel4.setText("Order ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 90, 40);

        jLabel1.setFont(new java.awt.Font("Utsaah", 1, 36)); // NOI18N
        jLabel1.setText("Credit Detail");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 270, 80);

        orderIDText.setEditable(false);
        orderIDText.setBackground(new java.awt.Color(204, 204, 204));
        orderIDText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        getContentPane().add(orderIDText);
        orderIDText.setBounds(170, 100, 120, 40);

        currentDateText.setEditable(false);
        currentDateText.setBackground(new java.awt.Color(204, 204, 204));
        currentDateText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        currentDateText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(currentDateText);
        currentDateText.setBounds(170, 150, 120, 40);

        jLabel6.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel6.setText("Current Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 150, 120, 40);

        stateText.setEditable(false);
        stateText.setBackground(new java.awt.Color(204, 204, 204));
        stateText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        stateText.setText("Pending");
        getContentPane().add(stateText);
        stateText.setBounds(170, 200, 120, 40);

        jLabel8.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel8.setText("State");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 200, 120, 40);

        jLabel9.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel9.setText("Amount");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 250, 120, 40);

        amountText.setBackground(new java.awt.Color(102, 255, 51));
        amountText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        amountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountTextKeyTyped(evt);
            }
        });
        getContentPane().add(amountText);
        amountText.setBounds(170, 250, 200, 40);

        saveButton.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveButtonMouseExited(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(170, 400, 130, 40);

        resetButton.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        resetButton.setText("RESET");
        getContentPane().add(resetButton);
        resetButton.setBounds(300, 400, 130, 40);

        balanceText.setBackground(new java.awt.Color(102, 255, 51));
        balanceText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        balanceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                balanceTextKeyTyped(evt);
            }
        });
        getContentPane().add(balanceText);
        balanceText.setBounds(170, 300, 200, 40);

        jLabel10.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel10.setText("Credit Balance");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 300, 180, 40);

        rpayment.setBackground(new java.awt.Color(102, 255, 51));
        rpayment.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        rpayment.setText("0");
        rpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpaymentActionPerformed(evt);
            }
        });
        rpayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rpaymentKeyTyped(evt);
            }
        });
        getContentPane().add(rpayment);
        rpayment.setBounds(170, 360, 200, 40);

        jLabel11.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel11.setText("Received Payment");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 360, 180, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

       
        int res = 0;
        if (amountText.getText().trim().equals("") || amountText.getText().trim().equals("0")) {

            JOptionPane.showMessageDialog(CreditDetail.this, "Amount can't be empty or " + "0");

        } else if (Double.parseDouble(balanceText.getText()) > Double.parseDouble(amountText.getText())) {

            JOptionPane.showMessageDialog(CreditDetail.this, "Are u nuts ?");

        } else {

            int yesOrNo = JOptionPane.showConfirmDialog(CreditDetail.this, "Do you want to SAVE this !", "Save", JOptionPane.YES_NO_OPTION);

            if (yesOrNo == 0) {

                String orderID = orderIDText.getText();

                String currentDate = currentDateText.getText();

                String state = stateText.getText();
                double amount = Double.parseDouble(amountText.getText());
                double balance = Double.parseDouble(balanceText.getText());
                double Received_Payment = Double.parseDouble(rpayment.getText());
                CreditDetailModel creditDetail = new CreditDetailModel(orderID, currentDate, state, amount, balance, Received_Payment);

                try {
                    res = CreditDetailController.addCreditDetail(creditDetail);
                } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(CreditDetail.this, ex);
                }

                if (res > 0) {

                    JOptionPane.showMessageDialog(CreditDetail.this, "Saved !");

                } else {

                    JOptionPane.showMessageDialog(CreditDetail.this, "Saving Fail !");

                }
            }
        }
        this.setVisible(false);
       
    }//GEN-LAST:event_saveButtonActionPerformed

    private void amountTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_amountTextKeyTyped

    private void balanceTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_balanceTextKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER)) {

            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_balanceTextKeyTyped

    private void amountTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextKeyPressed

        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {

            balanceText.setText(amountText.getText());
        }
    }//GEN-LAST:event_amountTextKeyPressed

    private void rpaymentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rpaymentKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER)) {

            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_rpaymentKeyTyped

    private void saveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseEntered
        Infor.setVisible(true);
    }//GEN-LAST:event_saveButtonMouseEntered

    private void saveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseExited
        Infor.setVisible(false);
    }//GEN-LAST:event_saveButtonMouseExited

    private void rpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpaymentActionPerformed
        balanceText.setText(Double.toString(Double.parseDouble(amountText.getText())-Double.parseDouble(rpayment.getText())));
    }//GEN-LAST:event_rpaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreditDetail dialog = new CreditDetail(new javax.swing.JFrame(), true,null,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Infor;
    private javax.swing.JTextField amountText;
    private javax.swing.JTextField balanceText;
    private javax.swing.JTextField currentDateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField orderIDText;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField rpayment;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField stateText;
    // End of variables declaration//GEN-END:variables
}
