/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import com.phone_shop.controller.ReportController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import java.text.DecimalFormat;
/**
 *
 * @author NisalSP9
 */
public class IncomeOfTheDayWS extends javax.swing.JDialog {

    private double total;

    /**
     * Creates new form FastMovingItemReport
     *
     * @param parent
     * @param modal
     */
    public IncomeOfTheDayWS(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();

        //get Current date
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date curDate = new Date();
        dateText.setText(dateFormat.format(curDate));

        try {
            updateTable(dateFormat.format(curDate));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(IncomeOfTheDayWS.class.getName()).log(Level.SEVERE, null, ex);
        }

        getTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateText = new javax.swing.JTextField();
        dateText1 = new javax.swing.JLabel();
        totalText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 380));
        setResizable(false);
        getContentPane().setLayout(null);

        dateText.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        dateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextActionPerformed(evt);
            }
        });
        getContentPane().add(dateText);
        dateText.setBounds(370, 10, 180, 40);

        dateText1.setFont(new java.awt.Font("Utsaah", 0, 36)); // NOI18N
        dateText1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateText1.setText("Total");
        getContentPane().add(dateText1);
        dateText1.setBounds(120, 180, 120, 30);

        totalText.setFont(new java.awt.Font("Utsaah", 0, 36)); // NOI18N
        totalText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalText.setText("7878");
        getContentPane().add(totalText);
        totalText.setBounds(250, 180, 300, 30);

        jLabel2.setFont(new java.awt.Font("Utsaah", 0, 36)); // NOI18N
        jLabel2.setText("Income Reports Wholesales");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 14, 350, 30);

        jTable1.setBackground(new java.awt.Color(1, 139, 186));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 530, 130);

        jButton1.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("View Chart");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 300, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1250, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        DefaultPieDataset dataset = new DefaultPieDataset();

        JFreeChart freeChart = null;

        for (int i = 0; i < model.getRowCount(); i++) {

            dataset.setValue((String) model.getValueAt(i, 1), (java.math.BigDecimal) model.getValueAt(i, 2));

        }
        freeChart = ChartFactory.createPieChart("Income Report", dataset, true, true, true);
        PiePlot piePlot = (PiePlot) freeChart.getPlot();

        ChartFrame chartFrame = new ChartFrame("", freeChart);

        chartFrame.setVisible(true);
        chartFrame.setSize(900, 700);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void dateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextActionPerformed
        total = 0;
        try {
            updateTable(dateText.getText());
            getTotal();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(IncomeOfTheDayWS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dateTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncomeOfTheDayWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncomeOfTheDayWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncomeOfTheDayWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncomeOfTheDayWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IncomeOfTheDayWS dialog = new IncomeOfTheDayWS(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void updateTable(String date) throws SQLException, ClassNotFoundException {

        ReportController rc = new ReportController();

        ResultSet rst;

        rst = rc.incomeOfTheDayForAllPaymentsWS(date);

        if (rst == null) {
            
            JOptionPane.showMessageDialog(IncomeOfTheDayWS.this,"No Income For Given Date");
        } else {

            jTable1.setModel(DbUtils.resultSetToTableModel(rst));

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateText;
    private javax.swing.JLabel dateText1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel totalText;
    // End of variables declaration//GEN-END:variables

    private void getTotal() {

        DecimalFormat df = new DecimalFormat("00.00");
        df.setMaximumFractionDigits(2);
        
        
        for (int i = 0; i < jTable1.getRowCount(); i++) {

            total += Double.parseDouble(jTable1.getValueAt(i, 2).toString());

        }

        totalText.setText(df.format(total) + "");

    }
}
