/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import com.phone_shop.controller.OrderController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultFocusManager;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author NisalSP9
 */
public final class Manage_Order_View extends javax.swing.JDialog {

    private int offset = 0;
    String userName = null;

    /**
     * Creates new form Manage_Order_View
     *
     * @param parent
     * @param modal
     * @param name
     */
    public Manage_Order_View(java.awt.Frame parent, boolean modal, String name) {
        //super(parent, modal);
        initComponents();
        updateAccessoricesTableALL(offset);

        userName = name;
        //get Current date
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date curDate = new Date();
        dateText.setText(dateFormat.format(curDate));

        //Clock
        final DateFormat instanceTime = DateFormat.getTimeInstance(SimpleDateFormat.MEDIUM);
        Timer timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                String format = instanceTime.format(d);
                clockLable.setText(instanceTime.format(d));

            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        clockLable = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        addOrderButton = new javax.swing.JButton();
        searchItemButton = new javax.swing.JButton();
        deteleFishItemButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        perButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 10, 0, 0));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Powered By CIS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(990, 620, 100, 50);

        jButton6.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        jButton6.setText("X");
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1150, 0, 50, 30);

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("View All Orders");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 1150, 40);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        jLabel1.setText("Manage Order");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 240, 50);

        orderTable.setBackground(new java.awt.Color(1, 139, 186));
        orderTable.setFont(new java.awt.Font("Utsaah", 0, 20)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Name", "Size", "description", "Unit Price", "QTY On Hand"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.setEnabled(false);
        jScrollPane2.setViewportView(orderTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 220, 1180, 400);

        clockLable.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        clockLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clockLable.setText("7878");
        getContentPane().add(clockLable);
        clockLable.setBounds(1010, 60, 170, 30);

        dateText.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        dateText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateText.setText("7878");
        getContentPane().add(dateText);
        dateText.setBounds(1010, 30, 170, 30);

        addOrderButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        addOrderButton.setText("New Order");
        addOrderButton.setBorder(null);
        addOrderButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOrderButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderButtonActionPerformed(evt);
            }
        });
        addOrderButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addOrderButtonKeyPressed(evt);
            }
        });
        getContentPane().add(addOrderButton);
        addOrderButton.setBounds(360, 110, 150, 50);

        searchItemButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        searchItemButton.setText("Find Order");
        searchItemButton.setBorder(null);
        searchItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemButtonActionPerformed(evt);
            }
        });
        searchItemButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchItemButtonKeyPressed(evt);
            }
        });
        getContentPane().add(searchItemButton);
        searchItemButton.setBounds(510, 110, 150, 50);

        deteleFishItemButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        deteleFishItemButton.setText("Remove");
        deteleFishItemButton.setBorder(null);
        deteleFishItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deteleFishItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deteleFishItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deteleFishItemButtonActionPerformed(evt);
            }
        });
        deteleFishItemButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deteleFishItemButtonKeyPressed(evt);
            }
        });
        getContentPane().add(deteleFishItemButton);
        deteleFishItemButton.setBounds(660, 110, 150, 50);

        nextButton.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        nextButton.setForeground(new java.awt.Color(204, 204, 204));
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/next.png"))); // NOI18N
        nextButton.setBorder(null);
        nextButton.setContentAreaFilled(false);
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        nextButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nextButtonKeyPressed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(1140, 620, 49, 50);

        perButton.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        perButton.setForeground(new java.awt.Color(204, 204, 204));
        perButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Extras-Backward-icon.png"))); // NOI18N
        perButton.setBorder(null);
        perButton.setContentAreaFilled(false);
        perButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perButtonActionPerformed(evt);
            }
        });
        perButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                perButtonKeyPressed(evt);
            }
        });
        getContentPane().add(perButton);
        perButton.setBounds(1090, 620, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1320, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButtonActionPerformed

        new Place_Customer_Order(null, rootPaneCheckingEnabled, userName).setVisible(true);
    }//GEN-LAST:event_addOrderButtonActionPerformed

    private void addOrderButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addOrderButtonKeyPressed

    }//GEN-LAST:event_addOrderButtonKeyPressed

    private void searchItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemButtonActionPerformed
        new SearchOrderView(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_searchItemButtonActionPerformed

    private void searchItemButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchItemButtonKeyPressed
        int iKey = evt.getKeyCode();
        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
    }//GEN-LAST:event_searchItemButtonKeyPressed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        if (!(orderTable.getModel().getRowCount() == 0)) {

            perButton.setEnabled(true);

            offset += 29;

            updateAccessoricesTableALL(offset);

        } else {

            nextButton.setEnabled(false);

        }


    }//GEN-LAST:event_nextButtonActionPerformed

    private void nextButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nextButtonKeyPressed
        int iKey = evt.getKeyCode();
        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
    }//GEN-LAST:event_nextButtonKeyPressed

    private void deteleFishItemButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deteleFishItemButtonKeyPressed
        int iKey = evt.getKeyCode();
        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
    }//GEN-LAST:event_deteleFishItemButtonKeyPressed

    private void deteleFishItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deteleFishItemButtonActionPerformed
        new SearchOrderView(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_deteleFishItemButtonActionPerformed

    private void perButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perButtonActionPerformed
//        offset -= 26;
//        
//        orderListnextButton.setEnabled(true);
//        
//        if (offset > 0) {
//            updateAccessoricesTableALL(offset);
//        } else {
//            orderListpreButton.setEnabled(false);
//        }

        if (offset <= 0) {

            perButton.setEnabled(false);

        } else {

            nextButton.setEnabled(true);

            offset -= 29;

            updateAccessoricesTableALL(offset);

        }


    }//GEN-LAST:event_perButtonActionPerformed

    private void perButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_perButtonKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int rst = JOptionPane.showConfirmDialog(Manage_Order_View.this, "Do you want exit ?", "Exit", 0);

        if (rst == 0) {

            dispose();

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Order_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Order_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Order_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Order_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Manage_Order_View dialog = new Manage_Order_View(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void updateAccessoricesTableALL(int offset) {
        OrderController orderController = new OrderController();
        try {
            ResultSet rst = orderController.updateOrderTableALL(offset);
            orderTable.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrderButton;
    private javax.swing.JLabel clockLable;
    private javax.swing.JLabel dateText;
    private javax.swing.JButton deteleFishItemButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextButton;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton perButton;
    private javax.swing.JButton searchItemButton;
    // End of variables declaration//GEN-END:variables
}
