/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import com.phone_shop.controller.SupplierController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultFocusManager;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author NisalSP9
 */
public class Manage_Suppliers_View extends javax.swing.JDialog {

    private int offset = 0;

    /**
     * Creates new form Manage_Suppliers_View
     */
    public Manage_Suppliers_View(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        viewAllSupplier(offset);

        //get Current date
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date curDate = new Date();
        dateText.setText(dateFormat.format(curDate));

        //Clock
        final DateFormat instanceTime = DateFormat.getTimeInstance(SimpleDateFormat.MEDIUM);
        Timer timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                String format = instanceTime.format(d);
                clockLable.setText(instanceTime.format(d));

            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ViewCustomerTable = new javax.swing.JTable();
        clockLable = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        addCustomerButton3 = new javax.swing.JButton();
        searchCustomerButton = new javax.swing.JButton();
        updateCustomerButton4 = new javax.swing.JButton();
        deteleCustomerButton1 = new javax.swing.JButton();
        viewNextCustomerButton = new javax.swing.JButton();
        viewPerCustomerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 10, 10, 10));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        ViewCustomerTable.setBackground(new java.awt.Color(1, 139, 186));
        ViewCustomerTable.setFont(new java.awt.Font("Utsaah", 0, 20)); // NOI18N
        ViewCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "description", "Address", "Mobile", "Land Line", "email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ViewCustomerTable.setMaximumSize(new java.awt.Dimension(450, 64));
        ViewCustomerTable.setMinimumSize(new java.awt.Dimension(450, 64));
        jScrollPane2.setViewportView(ViewCustomerTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 250, 1160, 370);

        clockLable.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        clockLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clockLable.setText("7878");
        getContentPane().add(clockLable);
        clockLable.setBounds(910, 80, 260, 30);

        dateText.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        dateText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateText.setText("7878");
        getContentPane().add(dateText);
        dateText.setBounds(940, 50, 230, 30);

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Powered By CIS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(970, 620, 100, 40);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        jLabel1.setText("Manage Suppliers");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 320, 70);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View All Suppliers");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 200, 1160, 40);

        jButton6.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        jButton6.setText("X");
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1130, 0, 50, 30);

        addCustomerButton3.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        addCustomerButton3.setText("New Supplier");
        addCustomerButton3.setBorder(null);
        addCustomerButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addCustomerButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addCustomerButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButton3ActionPerformed(evt);
            }
        });
        addCustomerButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addCustomerButton3KeyPressed(evt);
            }
        });
        getContentPane().add(addCustomerButton3);
        addCustomerButton3.setBounds(310, 120, 140, 50);

        searchCustomerButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        searchCustomerButton.setText("Find Suppliers");
        searchCustomerButton.setBorder(null);
        searchCustomerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchCustomerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerButtonActionPerformed(evt);
            }
        });
        searchCustomerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchCustomerButtonKeyPressed(evt);
            }
        });
        getContentPane().add(searchCustomerButton);
        searchCustomerButton.setBounds(450, 120, 140, 50);

        updateCustomerButton4.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        updateCustomerButton4.setText("Modify Infor");
        updateCustomerButton4.setBorder(null);
        updateCustomerButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateCustomerButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateCustomerButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButton4ActionPerformed(evt);
            }
        });
        updateCustomerButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateCustomerButton4KeyPressed(evt);
            }
        });
        getContentPane().add(updateCustomerButton4);
        updateCustomerButton4.setBounds(590, 120, 140, 50);

        deteleCustomerButton1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        deteleCustomerButton1.setText("Remove");
        deteleCustomerButton1.setBorder(null);
        deteleCustomerButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deteleCustomerButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deteleCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deteleCustomerButton1ActionPerformed(evt);
            }
        });
        deteleCustomerButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deteleCustomerButton1KeyPressed(evt);
            }
        });
        getContentPane().add(deteleCustomerButton1);
        deteleCustomerButton1.setBounds(730, 120, 140, 50);

        viewNextCustomerButton.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        viewNextCustomerButton.setForeground(new java.awt.Color(204, 204, 204));
        viewNextCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/next.png"))); // NOI18N
        viewNextCustomerButton.setContentAreaFilled(false);
        viewNextCustomerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewNextCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNextCustomerButtonActionPerformed(evt);
            }
        });
        viewNextCustomerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewNextCustomerButtonKeyPressed(evt);
            }
        });
        getContentPane().add(viewNextCustomerButton);
        viewNextCustomerButton.setBounds(1120, 620, 50, 40);

        viewPerCustomerButton.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        viewPerCustomerButton.setForeground(new java.awt.Color(204, 204, 204));
        viewPerCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Extras-Backward-icon.png"))); // NOI18N
        viewPerCustomerButton.setContentAreaFilled(false);
        viewPerCustomerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewPerCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPerCustomerButtonActionPerformed(evt);
            }
        });
        viewPerCustomerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewPerCustomerButtonKeyPressed(evt);
            }
        });
        getContentPane().add(viewPerCustomerButton);
        viewPerCustomerButton.setBounds(1070, 620, 50, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1320, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButton3ActionPerformed
        new Add_Supliers(null, rootPaneCheckingEnabled).setVisible(true);

    }//GEN-LAST:event_addCustomerButton3ActionPerformed

    private void addCustomerButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addCustomerButton3KeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }

        if (iKey == KeyEvent.VK_ENTER) {
            new AddCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_addCustomerButton3KeyPressed

    private void searchCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerButtonActionPerformed
        new Search_Suppliers(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_searchCustomerButtonActionPerformed

    private void searchCustomerButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCustomerButtonKeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
        if (iKey == KeyEvent.VK_ENTER) {
            new SearchCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_searchCustomerButtonKeyPressed

    private void updateCustomerButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButton4ActionPerformed
        new Update_Supplier_View(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_updateCustomerButton4ActionPerformed

    private void updateCustomerButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateCustomerButton4KeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
        if (iKey == KeyEvent.VK_ENTER) {
            new UpdateCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_updateCustomerButton4KeyPressed

    private void deteleCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deteleCustomerButton1ActionPerformed
        new Delete_Supplier_View(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_deteleCustomerButton1ActionPerformed

    private void deteleCustomerButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deteleCustomerButton1KeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
        if (iKey == KeyEvent.VK_ENTER) {
            new DeleteCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_deteleCustomerButton1KeyPressed

    private void viewNextCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNextCustomerButtonActionPerformed
         if (!( ViewCustomerTable.getModel().getRowCount()==0)) {

            viewPerCustomerButton.setEnabled(true);
                        


            offset += 27;

            viewAllSupplier(offset);

        } else {

            viewNextCustomerButton.setEnabled(false);

        }


    }//GEN-LAST:event_viewNextCustomerButtonActionPerformed

    private void viewNextCustomerButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewNextCustomerButtonKeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
    }//GEN-LAST:event_viewNextCustomerButtonKeyPressed

    private void viewPerCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPerCustomerButtonActionPerformed
        if (offset <= 0) {

            viewPerCustomerButton.setEnabled(false);

        } else {

            viewNextCustomerButton.setEnabled(true);

            offset -= 27;

            viewAllSupplier(offset);

        }


    }//GEN-LAST:event_viewPerCustomerButtonActionPerformed

    private void viewPerCustomerButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewPerCustomerButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPerCustomerButtonKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int rst = JOptionPane.showConfirmDialog(Manage_Suppliers_View.this, "Do you want exit ?", "Exit", 0);

        if (rst == 0) {

            dispose();

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Suppliers_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Suppliers_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Suppliers_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Suppliers_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Manage_Suppliers_View dialog = new Manage_Suppliers_View(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void viewAllSupplier(int offset) {
        SupplierController suppliercontroller = new SupplierController();
        try {
            ResultSet rst = suppliercontroller.viewAllTable(offset);
            ViewCustomerTable.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ViewCustomerTable;
    private javax.swing.JButton addCustomerButton3;
    private javax.swing.JLabel clockLable;
    private javax.swing.JLabel dateText;
    private javax.swing.JButton deteleCustomerButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchCustomerButton;
    private javax.swing.JButton updateCustomerButton4;
    private javax.swing.JButton viewNextCustomerButton;
    private javax.swing.JButton viewPerCustomerButton;
    // End of variables declaration//GEN-END:variables
}
