/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import com.phone_shop.controller.CustomerController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultFocusManager;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author NisalSP9
 */
public final class Manage_Customer_View extends javax.swing.JDialog {

    /**
     * Creates new form Manage_Customer_View
     */
    private int offset = 0;
    
   
            

    public Manage_Customer_View(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        updateTableCustomer(offset);
         //get Current date
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date curDate = new Date();
        dateText.setText(dateFormat.format(curDate));

        //Clock
        final DateFormat instanceTime = DateFormat.getTimeInstance(SimpleDateFormat.MEDIUM);
        Timer timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                String format = instanceTime.format(d);
                clockLable.setText(instanceTime.format(d));

            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clockLable = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewCustomerTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchCustomerButton = new javax.swing.JButton();
        deteleCustomerButton1 = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        addCustomerButton3 = new javax.swing.JButton();
        updateCustomerButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Customer");
        setBounds(new java.awt.Rectangle(50, 10, 50, 10));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        jButton1.setText("X");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1140, 0, 50, 30);

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Powered By CIS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(990, 650, 100, 30);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        jLabel1.setText("Manage Customer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 610, 50);

        clockLable.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        clockLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clockLable.setText("7878");
        getContentPane().add(clockLable);
        clockLable.setBounds(850, 70, 330, 30);

        dateText.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        dateText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateText.setText("7878");
        getContentPane().add(dateText);
        dateText.setBounds(850, 40, 330, 30);

        ViewCustomerTable.setBackground(new java.awt.Color(1, 139, 186));
        ViewCustomerTable.setFont(new java.awt.Font("Utsaah", 0, 20)); // NOI18N
        ViewCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIC Number", "First Name", "Last Name", "Address", "Mobile Number", "Land Line", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ViewCustomerTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ViewCustomerTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ViewCustomerTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(ViewCustomerTable);
        if (ViewCustomerTable.getColumnModel().getColumnCount() > 0) {
            ViewCustomerTable.getColumnModel().getColumn(3).setPreferredWidth(300);
            ViewCustomerTable.getColumnModel().getColumn(3).setMaxWidth(500);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 1180, 410);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View All Customers");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 190, 1180, 30);

        searchCustomerButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        searchCustomerButton.setText("Find");
        searchCustomerButton.setBorder(null);
        searchCustomerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        searchCustomerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchCustomerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerButtonActionPerformed(evt);
            }
        });
        searchCustomerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchCustomerButtonKeyPressed(evt);
            }
        });
        getContentPane().add(searchCustomerButton);
        searchCustomerButton.setBounds(490, 110, 140, 50);

        deteleCustomerButton1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        deteleCustomerButton1.setText("Remove");
        deteleCustomerButton1.setBorder(null);
        deteleCustomerButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deteleCustomerButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deteleCustomerButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deteleCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deteleCustomerButton1ActionPerformed(evt);
            }
        });
        deteleCustomerButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deteleCustomerButton1KeyPressed(evt);
            }
        });
        getContentPane().add(deteleCustomerButton1);
        deteleCustomerButton1.setBounds(770, 110, 140, 50);

        nextButton.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        nextButton.setForeground(new java.awt.Color(204, 204, 204));
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/next.png"))); // NOI18N
        nextButton.setBorder(null);
        nextButton.setContentAreaFilled(false);
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        nextButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nextButtonKeyPressed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(1140, 640, 50, 50);

        previousButton.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        previousButton.setForeground(new java.awt.Color(204, 204, 204));
        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Extras-Backward-icon.png"))); // NOI18N
        previousButton.setBorder(null);
        previousButton.setContentAreaFilled(false);
        previousButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        previousButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        previousButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                previousButtonKeyPressed(evt);
            }
        });
        getContentPane().add(previousButton);
        previousButton.setBounds(1090, 640, 50, 50);

        addCustomerButton3.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        addCustomerButton3.setText("New Customer");
        addCustomerButton3.setToolTipText("Add New Customer");
        addCustomerButton3.setBorder(null);
        addCustomerButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addCustomerButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addCustomerButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addCustomerButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButton3ActionPerformed(evt);
            }
        });
        addCustomerButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addCustomerButton3KeyPressed(evt);
            }
        });
        getContentPane().add(addCustomerButton3);
        addCustomerButton3.setBounds(290, 110, 200, 50);

        updateCustomerButton4.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        updateCustomerButton4.setText("Modify");
        updateCustomerButton4.setBorder(null);
        updateCustomerButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateCustomerButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateCustomerButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateCustomerButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButton4ActionPerformed(evt);
            }
        });
        updateCustomerButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateCustomerButton4KeyPressed(evt);
            }
        });
        getContentPane().add(updateCustomerButton4);
        updateCustomerButton4.setBounds(630, 110, 140, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1330, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButton3ActionPerformed
        new AddCustomerView(null, rootPaneCheckingEnabled).setVisible(true);


    }//GEN-LAST:event_addCustomerButton3ActionPerformed

    private void searchCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerButtonActionPerformed
        new SearchCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_searchCustomerButtonActionPerformed

    private void deteleCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deteleCustomerButton1ActionPerformed
        new DeleteCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_deteleCustomerButton1ActionPerformed

    private void updateCustomerButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButton4ActionPerformed
        new UpdateCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_updateCustomerButton4ActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        
        if (!( ViewCustomerTable.getModel().getRowCount()==0)) {

            previousButton.setEnabled(true);
                        


            offset += 26;

            updateTableCustomer(offset);

        } else {

            nextButton.setEnabled(false);

        }
        
        


    }//GEN-LAST:event_nextButtonActionPerformed

    private void addCustomerButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addCustomerButton3KeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }

        if (iKey == KeyEvent.VK_ENTER) {
            new AddCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_addCustomerButton3KeyPressed

    private void searchCustomerButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCustomerButtonKeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
        if (iKey == KeyEvent.VK_ENTER) {
            new SearchCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_searchCustomerButtonKeyPressed

    private void updateCustomerButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateCustomerButton4KeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
        if (iKey == KeyEvent.VK_ENTER) {
            new UpdateCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_updateCustomerButton4KeyPressed

    private void deteleCustomerButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deteleCustomerButton1KeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
        if (iKey == KeyEvent.VK_ENTER) {
            new DeleteCustomerView(null, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_deteleCustomerButton1KeyPressed

    private void nextButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nextButtonKeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
    }//GEN-LAST:event_nextButtonKeyPressed

    private void ViewCustomerTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ViewCustomerTableKeyPressed

    }//GEN-LAST:event_ViewCustomerTableKeyPressed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed

        if (offset <= 0) {

            previousButton.setEnabled(false);

        } else {

            nextButton.setEnabled(true);

            offset -= 26;

            updateTableCustomer(offset);

        }

       }//GEN-LAST:event_previousButtonActionPerformed

    private void previousButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_previousButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousButtonKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int rst = JOptionPane.showConfirmDialog(Manage_Customer_View.this, "Do you want exit ?", "Exit", 0);

        if (rst == 0) {

            dispose();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Customer_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Customer_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Customer_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Customer_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Manage_Customer_View dialog = new Manage_Customer_View(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void updateTableCustomer(int offset) {

        CustomerController customercontroller = new CustomerController();
        try {
            ResultSet rst = customercontroller.customerListWithOffset(offset);
            ViewCustomerTable.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ViewCustomerTable;
    private javax.swing.JButton addCustomerButton3;
    private javax.swing.JLabel clockLable;
    private javax.swing.JLabel dateText;
    private javax.swing.JButton deteleCustomerButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton searchCustomerButton;
    private javax.swing.JButton updateCustomerButton4;
    // End of variables declaration//GEN-END:variables
}
