/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

//import com.phone_shop.controller.AccessoricesController;
import com.phone_shop.controller.ItemController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultFocusManager;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author NisalSP9
 */
public final class Manage_Item extends javax.swing.JDialog {

    int offset;

    public Manage_Item(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        updateAccessoricesTable(offset);

        //get Current date
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date curDate = new Date();
        dateText.setText(dateFormat.format(curDate));

        //Clock
        final DateFormat instanceTime = DateFormat.getTimeInstance(SimpleDateFormat.MEDIUM);
        Timer timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                String format = instanceTime.format(d);
                clockLable.setText(instanceTime.format(d));

            }
        });
        timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        dateText = new javax.swing.JLabel();
        clockLable = new javax.swing.JLabel();
        previousButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        accessoricesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        addItemButton = new javax.swing.JButton();
        searchItemButton = new javax.swing.JButton();
        updateItemButton = new javax.swing.JButton();
        deteleFishItemButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Accessorices");
        setBounds(new java.awt.Rectangle(50, 10, 50, 10));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Powered By CIS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(980, 650, 100, 50);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        jLabel1.setText("Manage Items");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 340, 60);

        jButton6.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        jButton6.setText("X");
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1150, 0, 50, 30);

        dateText.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        dateText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateText.setText("7878");
        getContentPane().add(dateText);
        dateText.setBounds(970, 30, 210, 30);

        clockLable.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        clockLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clockLable.setText("7878");
        getContentPane().add(clockLable);
        clockLable.setBounds(970, 60, 210, 30);

        previousButton.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        previousButton.setForeground(new java.awt.Color(204, 204, 204));
        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Extras-Backward-icon.png"))); // NOI18N
        previousButton.setBorder(null);
        previousButton.setContentAreaFilled(false);
        previousButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        previousButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                previousButtonKeyPressed(evt);
            }
        });
        getContentPane().add(previousButton);
        previousButton.setBounds(1080, 650, 50, 50);

        accessoricesTable.setBackground(new java.awt.Color(1, 139, 186));
        accessoricesTable.setFont(new java.awt.Font("Utsaah", 0, 20)); // NOI18N
        accessoricesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Name", "Size", "description", "Unit Price", "QTY On Hand"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accessoricesTable.setMaximumSize(new java.awt.Dimension(450, 64));
        accessoricesTable.setMinimumSize(new java.awt.Dimension(450, 64));
        jScrollPane2.setViewportView(accessoricesTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 240, 1170, 410);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View All Accessorices In Store");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 210, 1170, 30);

        addItemButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        addItemButton.setText("New Item");
        addItemButton.setBorder(null);
        addItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });
        addItemButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addItemButtonKeyPressed(evt);
            }
        });
        getContentPane().add(addItemButton);
        addItemButton.setBounds(360, 130, 130, 50);

        searchItemButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        searchItemButton.setText("Find Item");
        searchItemButton.setBorder(null);
        searchItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemButtonActionPerformed(evt);
            }
        });
        searchItemButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchItemButtonKeyPressed(evt);
            }
        });
        getContentPane().add(searchItemButton);
        searchItemButton.setBounds(490, 130, 130, 50);

        updateItemButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        updateItemButton.setText("Modify Infor");
        updateItemButton.setBorder(null);
        updateItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateItemButtonActionPerformed(evt);
            }
        });
        updateItemButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateItemButtonKeyPressed(evt);
            }
        });
        getContentPane().add(updateItemButton);
        updateItemButton.setBounds(620, 130, 130, 50);

        deteleFishItemButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        deteleFishItemButton.setText("Remove");
        deteleFishItemButton.setBorder(null);
        deteleFishItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deteleFishItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deteleFishItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deteleFishItemButtonActionPerformed(evt);
            }
        });
        deteleFishItemButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deteleFishItemButtonKeyPressed(evt);
            }
        });
        getContentPane().add(deteleFishItemButton);
        deteleFishItemButton.setBounds(750, 130, 130, 50);

        nextButton.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        nextButton.setForeground(new java.awt.Color(204, 204, 204));
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/next.png"))); // NOI18N
        nextButton.setToolTipText("");
        nextButton.setBorder(null);
        nextButton.setContentAreaFilled(false);
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        nextButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nextButtonKeyPressed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(1130, 650, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-16, -16, 1340, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed

        new Add_Item_View(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void addItemButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addItemButtonKeyPressed
        int iKey = evt.getKeyCode();

        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }

        if (iKey == KeyEvent.VK_ENTER) {
            new Add_Item_View(null, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_addItemButtonKeyPressed

    private void searchItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemButtonActionPerformed
        new Search_Item_View(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_searchItemButtonActionPerformed

    private void searchItemButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchItemButtonKeyPressed
        int iKey = evt.getKeyCode();
        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
    }//GEN-LAST:event_searchItemButtonKeyPressed

    private void updateItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateItemButtonActionPerformed
        new Update_Item_View(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_updateItemButtonActionPerformed

    private void updateItemButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateItemButtonKeyPressed
        int iKey = evt.getKeyCode();
        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
    }//GEN-LAST:event_updateItemButtonKeyPressed

    private void deteleFishItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deteleFishItemButtonActionPerformed
        new Delete_Item_View(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_deteleFishItemButtonActionPerformed

    private void deteleFishItemButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deteleFishItemButtonKeyPressed
        int iKey = evt.getKeyCode();
        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
    }//GEN-LAST:event_deteleFishItemButtonKeyPressed

    private void nextButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nextButtonKeyPressed
        int iKey = evt.getKeyCode();
        JComponent component = (JButton) evt.getComponent();
        DefaultFocusManager focusManager = new DefaultFocusManager();
        if ((iKey == KeyEvent.VK_DOWN) || (iKey == KeyEvent.VK_PAGE_DOWN) || (iKey == KeyEvent.VK_TAB)) {
            focusManager.focusNextComponent(component);
        }
        if ((iKey == KeyEvent.VK_UP) || (iKey == KeyEvent.VK_PAGE_UP)) {

            focusManager.focusPreviousComponent(component);
        }
    }//GEN-LAST:event_nextButtonKeyPressed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        offset += 27;

        previousButton.setEnabled(true);

        if (accessoricesTable.getModel().getRowCount() > 0) {

           updateAccessoricesTable(offset);

        } else {
            
            nextButton.setEnabled(false);
            
        }


    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        offset -= 27;
        
        nextButton.setEnabled(true);

        if (offset < 0) {

            previousButton.setEnabled(false);

        } else {

            updateAccessoricesTable(offset);

        }


    }//GEN-LAST:event_previousButtonActionPerformed

    private void previousButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_previousButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousButtonKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int rst = JOptionPane.showConfirmDialog(Manage_Item.this, "Do you want exit ?", "Exit", 0);

        if (rst == 0) {

            dispose();

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Manage_Item dialog = new Manage_Item(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void updateAccessoricesTable(int offset) {
        //AccessoricesController accessoricesController = new AccessoricesController();
        try {
            ResultSet rst = ItemController.itemListWithOffset(offset);
            accessoricesTable.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accessoricesTable;
    private javax.swing.JButton addItemButton;
    private javax.swing.JLabel clockLable;
    private javax.swing.JLabel dateText;
    private javax.swing.JButton deteleFishItemButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton searchItemButton;
    private javax.swing.JButton updateItemButton;
    // End of variables declaration//GEN-END:variables
}
