/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import com.phone_shop.controller.UserControll;
import com.phone_shop.model.User;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author NisalSP9
 */
public class ManageUserView extends javax.swing.JDialog {

    /**
     * Creates new form ManageUserView
     */
    public ManageUserView(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageUserTabbedPane = new javax.swing.JTabbedPane();
        addPanel = new javax.swing.JPanel();
        passwordLable = new javax.swing.JLabel();
        userNameLable = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        userNameText = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        privilageLable2 = new javax.swing.JLabel();
        privilageCB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        userNameLable2 = new javax.swing.JLabel();
        userNameText2 = new javax.swing.JTextField();
        deleteButton1 = new javax.swing.JButton();
        resetButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        deleteButton2 = new javax.swing.JButton();
        manageUserTitel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(570, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        addPanel.setLayout(null);

        passwordLable.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        passwordLable.setText("Password");
        addPanel.add(passwordLable);
        passwordLable.setBounds(10, 90, 160, 30);

        userNameLable.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        userNameLable.setText("User Name");
        addPanel.add(userNameLable);
        userNameLable.setBounds(10, 30, 160, 30);

        passwordText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        passwordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordTextKeyTyped(evt);
            }
        });
        addPanel.add(passwordText);
        passwordText.setBounds(170, 90, 280, 30);

        userNameText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        userNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextActionPerformed(evt);
            }
        });
        userNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userNameTextKeyTyped(evt);
            }
        });
        addPanel.add(userNameText);
        userNameText.setBounds(170, 30, 340, 30);

        resetButton.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        addPanel.add(resetButton);
        resetButton.setBounds(410, 290, 120, 40);

        addButton.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        addButton.setText("Save");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addPanel.add(addButton);
        addButton.setBounds(300, 290, 110, 40);

        privilageLable2.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        privilageLable2.setText("Privilage");
        addPanel.add(privilageLable2);
        privilageLable2.setBounds(10, 150, 140, 30);

        privilageCB.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        privilageCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User", "Admin" }));
        privilageCB.setToolTipText("");
        privilageCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privilageCBActionPerformed(evt);
            }
        });
        addPanel.add(privilageCB);
        privilageCB.setBounds(170, 150, 93, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        addPanel.add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 350);

        manageUserTabbedPane.addTab("New Users", addPanel);

        deletePanel.setLayout(null);

        userNameLable2.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        userNameLable2.setText("User Name");
        deletePanel.add(userNameLable2);
        userNameLable2.setBounds(10, 30, 120, 30);

        userNameText2.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        userNameText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameText2ActionPerformed(evt);
            }
        });
        userNameText2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userNameText2KeyTyped(evt);
            }
        });
        deletePanel.add(userNameText2);
        userNameText2.setBounds(200, 30, 310, 30);

        deleteButton1.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        deleteButton1.setText("Remove");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });
        deletePanel.add(deleteButton1);
        deleteButton1.setBounds(270, 290, 140, 40);

        resetButton2.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        resetButton2.setText("Reset");
        resetButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton2ActionPerformed(evt);
            }
        });
        deletePanel.add(resetButton2);
        resetButton2.setBounds(410, 290, 120, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        deletePanel.add(jLabel4);
        jLabel4.setBounds(0, 0, 550, 350);

        manageUserTabbedPane.addTab("Remove User", deletePanel);

        jPanel1.setLayout(null);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(-2, 5, 550, 280);

        deleteButton2.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        deleteButton2.setText("View");
        deleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton2);
        deleteButton2.setBounds(400, 290, 140, 40);

        manageUserTabbedPane.addTab("View All Users", jPanel1);

        getContentPane().add(manageUserTabbedPane);
        manageUserTabbedPane.setBounds(10, 50, 550, 380);

        manageUserTitel.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        manageUserTitel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageUserTitel.setText("Manage User");
        getContentPane().add(manageUserTitel);
        manageUserTitel.setBounds(0, 0, 610, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Admin privilage value = 10  Officer privilage value = 5  Check Post Officer privilage value = 1 
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        User user = new User(userNameText.getText(), privilageCB.getSelectedIndex(), passwordText.getText());
        UserControll userControll = new UserControll();
        try {
            int rst = userControll.addUser(user);

            if (rst > 0) {

                JOptionPane.showMessageDialog(ManageUserView.this, "Added...!");
                resetButton.doClick();

            } else {

                JOptionPane.showMessageDialog(ManageUserView.this, "Fail...!");

            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageUserView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        userNameText.setText("");
        passwordText.setText("");
        privilageCB.setSelectedIndex(0);

    }//GEN-LAST:event_resetButtonActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed

        UserControll userControll = new UserControll();

        try {
            int rst = userControll.deleteUser(userNameText2.getText());
            if (rst > 0) {

                JOptionPane.showMessageDialog(ManageUserView.this, "Deleted...!");
                resetButton2.doClick();

            } else {

                JOptionPane.showMessageDialog(ManageUserView.this, "Fail...!");

            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageUserView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void resetButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton2ActionPerformed
        userNameText2.setText("");
    }//GEN-LAST:event_resetButton2ActionPerformed

    private void privilageCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privilageCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_privilageCBActionPerformed

    private void userNameText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameText2ActionPerformed

    }//GEN-LAST:event_userNameText2ActionPerformed

    private void userNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextActionPerformed

    private void userNameTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTextKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || Character.isLetter(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_userNameTextKeyTyped

    private void passwordTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTextKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || Character.isLetter(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_passwordTextKeyTyped

    private void userNameText2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameText2KeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || Character.isLetter(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_userNameText2KeyTyped

    private void deleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton2ActionPerformed
        updateTableCustomer();
    }//GEN-LAST:event_deleteButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageUserView dialog = new ManageUserView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void updateTableCustomer() {

        UserControll usercontroller = new UserControll();
        try {
            ResultSet rst = usercontroller.showUsers();
            userTable.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JButton deleteButton2;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane manageUserTabbedPane;
    private javax.swing.JLabel manageUserTitel;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JTextField passwordText;
    private javax.swing.JComboBox privilageCB;
    private javax.swing.JLabel privilageLable2;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetButton2;
    private javax.swing.JLabel userNameLable;
    private javax.swing.JLabel userNameLable2;
    private javax.swing.JTextField userNameText;
    private javax.swing.JTextField userNameText2;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
