/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import com.phone_shop.controller.ChequeDetailController;
import com.phone_shop.controller.ItemController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author NisalSP9
 */
public final class OpenView extends javax.swing.JFrame {

    /**
     * Creates new form OpenView
     */
    String user = null;

    public OpenView(String User) {

        initComponents();

        updateItemReorderTable();
        updateChequePaymentAlertTable();
        this.user = User;
        welcome.setText(User);

        //get Current date
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date curDate = new Date();
        dateText.setText(dateFormat.format(curDate));

        //Clock
        final DateFormat instanceTime = DateFormat.getTimeInstance(SimpleDateFormat.MEDIUM);
        Timer timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();

                clockLable.setText(instanceTime.format(d));

            }
        });
        timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        orderMamgerButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clockLable = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        customerMamgerButton = new javax.swing.JButton();
        accessoricesMamgerButton = new javax.swing.JButton();
        orderMamgerButton = new javax.swing.JButton();
        paymentMamgerButton = new javax.swing.JButton();
        supplierMamgerButton = new javax.swing.JButton();
        userManager = new javax.swing.JButton();
        reportMamgerButton = new javax.swing.JButton();
        dateText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accessoricesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewChequeTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 10, 0, 0));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        jButton1.setText("X");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1140, 0, 45, 30);

        orderMamgerButton1.setBackground(new java.awt.Color(204, 204, 204));
        orderMamgerButton1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        orderMamgerButton1.setText("Service");
        orderMamgerButton1.setToolTipText("ORDER MANAGER where you can ADD (New Orders),Search Orders' Information and Delete  Accessorices's Information");
        orderMamgerButton1.setBorder(null);
        orderMamgerButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orderMamgerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderMamgerButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(orderMamgerButton1);
        orderMamgerButton1.setBounds(590, 170, 130, 50);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Powered By CIS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1090, 650, 100, 30);

        clockLable.setFont(new java.awt.Font("Utsaah", 0, 20)); // NOI18N
        clockLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clockLable.setText("1878");
        getContentPane().add(clockLable);
        clockLable.setBounds(960, 80, 210, 30);

        welcome.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        welcome.setText("NisalSP9");
        welcome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(welcome);
        welcome.setBounds(1020, 110, 150, 32);

        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("D & S Cellular");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 30, 240, 40);

        customerMamgerButton.setBackground(new java.awt.Color(204, 204, 204));
        customerMamgerButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        customerMamgerButton.setText("Customers");
        customerMamgerButton.setToolTipText("CUSTOMER MANAGER where you can ADD (New Cutomers),Search Customer Information,Update Customers' Information and Delete Customers' Information");
        customerMamgerButton.setBorder(null);
        customerMamgerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customerMamgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMamgerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(customerMamgerButton);
        customerMamgerButton.setBounds(70, 170, 130, 50);

        accessoricesMamgerButton.setBackground(new java.awt.Color(204, 204, 204));
        accessoricesMamgerButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        accessoricesMamgerButton.setText("Inventory");
        accessoricesMamgerButton.setToolTipText(" ACCESSORICES MANAGER where you can ADD (New Accessorices),Search  Accessorices' Information,Update Accessorices's Information and Delete  Accessorices's Information");
        accessoricesMamgerButton.setBorder(null);
        accessoricesMamgerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        accessoricesMamgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessoricesMamgerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(accessoricesMamgerButton);
        accessoricesMamgerButton.setBounds(200, 170, 130, 50);

        orderMamgerButton.setBackground(new java.awt.Color(204, 204, 204));
        orderMamgerButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        orderMamgerButton.setText("Sales");
        orderMamgerButton.setToolTipText("ORDER MANAGER where you can ADD (New Orders),Search Orders' Information and Delete  Accessorices's Information");
        orderMamgerButton.setBorder(null);
        orderMamgerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orderMamgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderMamgerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(orderMamgerButton);
        orderMamgerButton.setBounds(460, 170, 130, 50);

        paymentMamgerButton.setBackground(new java.awt.Color(204, 204, 204));
        paymentMamgerButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        paymentMamgerButton.setText("Payments");
        paymentMamgerButton.setToolTipText("PAYMENT MANAGER where you can manage Cash Payment,Credit Payment,Cheque Payment");
        paymentMamgerButton.setBorder(null);
        paymentMamgerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paymentMamgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentMamgerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(paymentMamgerButton);
        paymentMamgerButton.setBounds(850, 170, 130, 50);

        supplierMamgerButton.setBackground(new java.awt.Color(204, 204, 204));
        supplierMamgerButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        supplierMamgerButton.setText("Suppliers");
        supplierMamgerButton.setToolTipText("SUPPLIER MANAGER where you can Add Supplier Information,Search,Delete and Update");
        supplierMamgerButton.setBorder(null);
        supplierMamgerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        supplierMamgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierMamgerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(supplierMamgerButton);
        supplierMamgerButton.setBounds(720, 170, 130, 50);

        userManager.setBackground(new java.awt.Color(204, 204, 204));
        userManager.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        userManager.setText("Users ");
        userManager.setToolTipText("Where you can add new users to the system");
        userManager.setBorder(null);
        userManager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagerActionPerformed(evt);
            }
        });
        getContentPane().add(userManager);
        userManager.setBounds(980, 170, 130, 50);

        reportMamgerButton.setBackground(new java.awt.Color(204, 204, 204));
        reportMamgerButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        reportMamgerButton.setText("Reports");
        reportMamgerButton.setToolTipText("Where you can see reports");
        reportMamgerButton.setBorder(null);
        reportMamgerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportMamgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportMamgerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(reportMamgerButton);
        reportMamgerButton.setBounds(330, 170, 130, 50);

        dateText.setFont(new java.awt.Font("Utsaah", 0, 36)); // NOI18N
        dateText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateText.setText("7878");
        getContentPane().add(dateText);
        dateText.setBounds(960, 40, 210, 30);

        accessoricesTable.setBackground(new java.awt.Color(1, 139, 186));
        accessoricesTable.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        accessoricesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        accessoricesTable.setEnabled(false);
        accessoricesTable.setGridColor(new java.awt.Color(51, 51, 51));
        accessoricesTable.setSelectionBackground(new java.awt.Color(51, 51, 51));
        accessoricesTable.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(accessoricesTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 300, 590, 350);

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reorder Level reached Items");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 260, 590, 40);

        viewChequeTable.setBackground(new java.awt.Color(1, 139, 186));
        viewChequeTable.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        viewChequeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        viewChequeTable.setEnabled(false);
        viewChequeTable.setGridColor(new java.awt.Color(51, 51, 51));
        viewChequeTable.setSelectionBackground(new java.awt.Color(51, 51, 51));
        viewChequeTable.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane3.setViewportView(viewChequeTable);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(600, 300, 590, 350);

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cheque To be Deposited");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 260, 590, 40);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1360, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerMamgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMamgerButtonActionPerformed
        new Manage_Customer_View(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_customerMamgerButtonActionPerformed

    private void accessoricesMamgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessoricesMamgerButtonActionPerformed
        new Manage_Item(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_accessoricesMamgerButtonActionPerformed

    private void orderMamgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderMamgerButtonActionPerformed
        new Manage_Order_View(this, rootPaneCheckingEnabled, user).setVisible(true);
    }//GEN-LAST:event_orderMamgerButtonActionPerformed

    private void paymentMamgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMamgerButtonActionPerformed
        new ManagePayment(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_paymentMamgerButtonActionPerformed

    private void supplierMamgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierMamgerButtonActionPerformed
        new Manage_Suppliers_View(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_supplierMamgerButtonActionPerformed

    private void userManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagerActionPerformed
        new ManageUserView(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_userManagerActionPerformed

    private void reportMamgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportMamgerButtonActionPerformed
        new ReportMainView(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_reportMamgerButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int rst = JOptionPane.showConfirmDialog(OpenView.this, "Do you want exit ?", "Exit", 0);

        if (rst == 0) {

            System.exit(0);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void orderMamgerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderMamgerButton1ActionPerformed
        new Service(this, rootPaneCheckingEnabled, user).setVisible(true);
    }//GEN-LAST:event_orderMamgerButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OpenView(null).setVisible(true);
            }
        });
    }

    public void updateItemReorderTable() {
        ItemController itemController = new ItemController();
        try {
            ResultSet rst = itemController.updateItemReorderTable();
            accessoricesTable.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void updateChequePaymentAlertTable() {

        ChequeDetailController chequePayment = new ChequeDetailController();
        try {
            ResultSet rst = chequePayment.updateChequePaymentAlertTable();
            viewChequeTable.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessoricesMamgerButton;
    private javax.swing.JTable accessoricesTable;
    private javax.swing.JLabel clockLable;
    private javax.swing.JButton customerMamgerButton;
    private javax.swing.JLabel dateText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton orderMamgerButton;
    private javax.swing.JButton orderMamgerButton1;
    private javax.swing.JButton paymentMamgerButton;
    private javax.swing.JButton reportMamgerButton;
    private javax.swing.JButton supplierMamgerButton;
    private javax.swing.JButton userManager;
    private javax.swing.JTable viewChequeTable;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
