/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import javax.swing.JOptionPane;

/**
 *
 * @author NisalSP9
 */
public class ReportMainView extends javax.swing.JDialog {

    /**
     * Creates new form ReportMainView
     * @param parent
     * @param modal
     */
    public ReportMainView(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RCincomeReport = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        incomeReportButton = new javax.swing.JButton();
        RCincomeReport1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mostVaulableCutomerButton = new javax.swing.JButton();
        fastMovingItemButton = new javax.swing.JButton();
        mostValuableItemButton = new javax.swing.JButton();
        highestCreditHolderButton = new javax.swing.JButton();
        mostChequeReceivingBankButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 10, 0, 0));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        RCincomeReport.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        RCincomeReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Places-user-identity-icon.png"))); // NOI18N
        RCincomeReport.setText("Income Report For Retail Sales ");
        RCincomeReport.setBorder(null);
        RCincomeReport.setContentAreaFilled(false);
        RCincomeReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RCincomeReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RCincomeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCincomeReportActionPerformed(evt);
            }
        });
        getContentPane().add(RCincomeReport);
        RCincomeReport.setBounds(800, 330, 340, 170);

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Powered By CIS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1080, 650, 100, 50);

        jButton6.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        jButton6.setText("X");
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1140, 0, 50, 30);

        incomeReportButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        incomeReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/income.png"))); // NOI18N
        incomeReportButton.setText("Income Report");
        incomeReportButton.setBorder(null);
        incomeReportButton.setContentAreaFilled(false);
        incomeReportButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        incomeReportButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        incomeReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeReportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(incomeReportButton);
        incomeReportButton.setBounds(570, 320, 230, 240);

        RCincomeReport1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        RCincomeReport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/face.png"))); // NOI18N
        RCincomeReport1.setText("Income Report For Wholesales");
        RCincomeReport1.setBorder(null);
        RCincomeReport1.setContentAreaFilled(false);
        RCincomeReport1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RCincomeReport1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RCincomeReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCincomeReport1ActionPerformed(evt);
            }
        });
        getContentPane().add(RCincomeReport1);
        RCincomeReport1.setBounds(750, 120, 340, 200);

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        jLabel2.setText("Report Manager");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 270, 60);

        mostVaulableCutomerButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        mostVaulableCutomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Places-user-identity-icon.png"))); // NOI18N
        mostVaulableCutomerButton.setText("Most Valuable Customers");
        mostVaulableCutomerButton.setBorder(null);
        mostVaulableCutomerButton.setContentAreaFilled(false);
        mostVaulableCutomerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mostVaulableCutomerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mostVaulableCutomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostVaulableCutomerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mostVaulableCutomerButton);
        mostVaulableCutomerButton.setBounds(490, 150, 260, 170);

        fastMovingItemButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        fastMovingItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Shopping-cart-insert-icon (2).png"))); // NOI18N
        fastMovingItemButton.setText("Fast Moving Items");
        fastMovingItemButton.setBorder(null);
        fastMovingItemButton.setContentAreaFilled(false);
        fastMovingItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fastMovingItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fastMovingItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastMovingItemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(fastMovingItemButton);
        fastMovingItemButton.setBounds(70, 150, 200, 170);

        mostValuableItemButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        mostValuableItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Shopping-cart-accept-icon (1).png"))); // NOI18N
        mostValuableItemButton.setText("Most Valuable Items");
        mostValuableItemButton.setBorder(null);
        mostValuableItemButton.setContentAreaFilled(false);
        mostValuableItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mostValuableItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mostValuableItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostValuableItemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mostValuableItemButton);
        mostValuableItemButton.setBounds(270, 150, 220, 170);

        highestCreditHolderButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        highestCreditHolderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Invoice-icon.png"))); // NOI18N
        highestCreditHolderButton.setText("Highest Credit Holder");
        highestCreditHolderButton.setBorder(null);
        highestCreditHolderButton.setContentAreaFilled(false);
        highestCreditHolderButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        highestCreditHolderButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        highestCreditHolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highestCreditHolderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(highestCreditHolderButton);
        highestCreditHolderButton.setBounds(350, 320, 220, 200);

        mostChequeReceivingBankButton.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        mostChequeReceivingBankButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Bank-icon.png"))); // NOI18N
        mostChequeReceivingBankButton.setText("Most Cheque Receiving Bank");
        mostChequeReceivingBankButton.setBorder(null);
        mostChequeReceivingBankButton.setContentAreaFilled(false);
        mostChequeReceivingBankButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mostChequeReceivingBankButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mostChequeReceivingBankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostChequeReceivingBankButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mostChequeReceivingBankButton);
        mostChequeReceivingBankButton.setBounds(70, 320, 280, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fastMovingItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastMovingItemButtonActionPerformed
       new FastMovingItemReport(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_fastMovingItemButtonActionPerformed

    private void mostValuableItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostValuableItemButtonActionPerformed
        new MostValuableItemReport(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_mostValuableItemButtonActionPerformed

    private void mostVaulableCutomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostVaulableCutomerButtonActionPerformed
        new MostValuableCustomer(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_mostVaulableCutomerButtonActionPerformed

    private void highestCreditHolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highestCreditHolderButtonActionPerformed
        new HighsetCreditHolderView(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_highestCreditHolderButtonActionPerformed

    private void mostChequeReceivingBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostChequeReceivingBankButtonActionPerformed
        new MostChequeReceivingBank(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_mostChequeReceivingBankButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int rst = JOptionPane.showConfirmDialog(ReportMainView.this, "Do you want exit ?", "Exit", 0);

        if (rst == 0) {

            dispose();

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void incomeReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeReportButtonActionPerformed
        new IncomeOfTheDay(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_incomeReportButtonActionPerformed

    private void RCincomeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCincomeReportActionPerformed
       new IncomeOfTheDayRC(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_RCincomeReportActionPerformed

    private void RCincomeReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCincomeReport1ActionPerformed
        new IncomeOfTheDayWS(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_RCincomeReport1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReportMainView dialog = new ReportMainView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RCincomeReport;
    private javax.swing.JButton RCincomeReport1;
    private javax.swing.JButton fastMovingItemButton;
    private javax.swing.JButton highestCreditHolderButton;
    private javax.swing.JButton incomeReportButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton mostChequeReceivingBankButton;
    private javax.swing.JButton mostValuableItemButton;
    private javax.swing.JButton mostVaulableCutomerButton;
    // End of variables declaration//GEN-END:variables
}
