/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.phone_shop.view;

import com.phone_shop.controller.ChequeDetailController;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author NisalSP9
 */
public final class SearchChequePayment extends javax.swing.JDialog {

    //String id;
    /**
     * Creates new form SearchCashOrder
     *
     * @param parent
     * @param modal
     */
    public SearchChequePayment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        autoFillCB();
        trackEnterPressed();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        chequeNumberText = new javax.swing.JTextField();
        bankText = new javax.swing.JTextField();
        cusIDText = new javax.swing.JTextField();
        cusNameText = new javax.swing.JTextField();
        cashPayCB = new javax.swing.JComboBox();
        resetButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        RDateText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CDateText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        deleteButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(10, 10, 0, 0));
        setMaximumSize(new java.awt.Dimension(485, 621));
        setMinimumSize(new java.awt.Dimension(485, 621));
        setPreferredSize(new java.awt.Dimension(485, 621));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel1.setText("Search Cash Payment");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 0, 370, 70);

        jLabel2.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel2.setText("Order ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 110, 40);

        jLabel3.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel3.setText("Cheque Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 230, 150, 40);

        jLabel4.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel4.setText("Bank");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 280, 110, 40);

        jLabel5.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel5.setText("Amount");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 480, 110, 40);

        jLabel6.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel6.setText("Customer Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 180, 150, 40);

        amountText.setEditable(false);
        amountText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        getContentPane().add(amountText);
        amountText.setBounds(180, 480, 240, 40);

        chequeNumberText.setEditable(false);
        chequeNumberText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        getContentPane().add(chequeNumberText);
        chequeNumberText.setBounds(180, 230, 180, 40);

        bankText.setEditable(false);
        bankText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        getContentPane().add(bankText);
        bankText.setBounds(180, 280, 210, 40);

        cusIDText.setEditable(false);
        cusIDText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        getContentPane().add(cusIDText);
        cusIDText.setBounds(180, 130, 150, 40);

        cusNameText.setEditable(false);
        cusNameText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        getContentPane().add(cusNameText);
        cusNameText.setBounds(180, 180, 270, 40);

        cashPayCB.setEditable(true);
        cashPayCB.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        cashPayCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPayCBActionPerformed(evt);
            }
        });
        getContentPane().add(cashPayCB);
        cashPayCB.setBounds(180, 70, 180, 40);

        resetButton.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton);
        resetButton.setBounds(320, 540, 130, 40);

        jLabel8.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel8.setText("Customer ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 130, 110, 40);

        deleteButton.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(180, 540, 140, 40);

        jLabel9.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel9.setText("Received_Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 330, 150, 40);

        RDateText.setEditable(false);
        RDateText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        getContentPane().add(RDateText);
        RDateText.setBounds(180, 330, 210, 40);

        jLabel10.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel10.setText("Cheque_Date");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 380, 150, 40);

        CDateText.setEditable(false);
        CDateText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        getContentPane().add(CDateText);
        CDateText.setBounds(180, 380, 210, 40);

        jLabel11.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel11.setText("State");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 430, 110, 40);

        stateText.setEditable(false);
        stateText.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        getContentPane().add(stateText);
        stateText.setBounds(180, 430, 210, 40);

        deleteButton1.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        deleteButton1.setText("UPDATE");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton1);
        deleteButton1.setBounds(40, 540, 140, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phone_shop/view/pics/Win8BackGround-303030.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-50, -26, 600, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashPayCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPayCBActionPerformed

        itemInfor();


    }//GEN-LAST:event_cashPayCBActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        stateText.setText("");
        CDateText.setText("");
        RDateText.setText("");
        cusIDText.setText("");
        bankText.setText("");
        chequeNumberText.setText("");
        amountText.setText("");
        cusNameText.setText("");
        cashPayCB.removeAllItems();


    }//GEN-LAST:event_resetButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int okayORnot = JOptionPane.showConfirmDialog(null, "Do you really want to delete this ?", "Delete", JOptionPane.YES_NO_OPTION);

        if (okayORnot == 0) {
            try {
                int deleteOK = ChequeDetailController.deleteChequeDetail(cashPayCB.getSelectedItem().toString());

                if (deleteOK > 0) {

                    JOptionPane.showMessageDialog(SearchChequePayment.this, "Deleted !");
                    resetButton.doClick();
                    cashPayCB.removeAllItems();

                } else {

                    JOptionPane.showMessageDialog(SearchChequePayment.this, "Delete Fail !");
                }

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(SearchChequePayment.this, ex);
            }

        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
         int okayORnot = JOptionPane.showConfirmDialog(SearchChequePayment.this, "Do you really want to Update this ?", "Update", JOptionPane.YES_NO_OPTION);

        if (okayORnot == 0) {
            try {
                int deleteOK = ChequeDetailController.updateChequeDetail(cashPayCB.getSelectedItem().toString());

                if (deleteOK > 0) {

                    JOptionPane.showMessageDialog(SearchChequePayment.this, "Updated !");
                    resetButton.doClick();
                    cashPayCB.removeAllItems();

                } else {

                    JOptionPane.showMessageDialog(SearchChequePayment.this, "Update Fail !");
                }

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(SearchChequePayment.this, ex);
            }

        }
    }//GEN-LAST:event_deleteButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchChequePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchChequePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchChequePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchChequePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SearchChequePayment dialog = new SearchChequePayment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void autoFillCB() {

        cashPayCB.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent evt) {

                String Letter = cashPayCB.getEditor().getItem().toString();

                if (evt.getKeyCode() >= 48 || evt.getKeyCode() <= 57 || evt.getKeyCode() == 40 || evt.getKeyCode() == 38 || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER && Letter != null) {

                    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        nameSender(Letter);

                    }

                } else {

                    JOptionPane.showMessageDialog(SearchChequePayment.this, "Wrong Input...!");
                    cashPayCB.removeAllItems();
                    resetButton.doClick();

                }

            }

        });

    }

    public void nameSender(String Letter) {

        ChequeDetailController paymentController = new ChequeDetailController();

        try {

            if (paymentController.getList(Letter) != null) {

                cashPayCB.setModel(paymentController.getList(Letter));

            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Search_Item_View.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (cashPayCB.getItemCount() > 0) {

            cashPayCB.showPopup();

            itemInfor();

        }

    }

    public void itemInfor() {

        ChequeDetailController chequeDetailController = new ChequeDetailController();

        if (cashPayCB.isPopupVisible()) {
            String ID = cashPayCB.getSelectedItem().toString();

            System.out.println(ID);
            String order[] = null;
            try {
                order = chequeDetailController.giveAwayOrderInfro(ID);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(SearchChequePayment.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (order[0] == null) {

                JOptionPane.showMessageDialog(SearchChequePayment.this, "Can't Find...!");

                cashPayCB.removeAllItems();
                resetButton.doClick();

            } else {

                stateText.setText(order[4]);
                CDateText.setText(order[3]);
                RDateText.setText(order[2]);
                cusIDText.setText(order[0]);
                bankText.setText(order[1]);
                chequeNumberText.setText(order[0]);
                amountText.setText(order[5]);
                cusIDText.setText(order[6]);
                cusNameText.setText(order[7]);

            }

        } else {

            System.out.println("fffffffffffffffffffff");
           // resetButton.doClick();
        }

    }

    public void trackEnterPressed() {

        cashPayCB.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent evt) {

                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                    itemInfor();
                }

            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CDateText;
    private javax.swing.JTextField RDateText;
    private javax.swing.JTextField amountText;
    private javax.swing.JTextField bankText;
    private javax.swing.JComboBox cashPayCB;
    private javax.swing.JTextField chequeNumberText;
    private javax.swing.JTextField cusIDText;
    private javax.swing.JTextField cusNameText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField stateText;
    // End of variables declaration//GEN-END:variables
}
